services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=sgh_propia
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  springboot-app:
    build: .
    container_name: springboot-app
    depends_on:
      - mariadb
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/sgh_propia
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MariaDBDialect
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

volumes:
  mariadb_data:
  jenkins_home:

networks:
  app-network:
    driver: bridge

