spring.application.name=api_sgh
spring.datasource.url=jdbc:mariadb://mariadb:3306/sgh_propia
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.dialect=org.hibernate.dialect.MariaDbDialect
spring.jpa.hibernate.ddl-auto=none
server.port=8081